### ISSUE TITLE
Vanilla Enchantments

### ISSUE THREAD

**Issue by Haxley** [JackMD/MysteryCrate#37]
Vanilla enchantments don't appear to be working. No errors are thrown. Crate displays and gives items without enchantments.

Example crates.yml:
```
  rare:
      - name: "§d§lEpsilon Sword"
        id: 276
        meta: 0
        amount: 1
        enchantments:
          sharpness:
            level: 1
      - name: "§d§lEpsilon Chest"
        id: 311
        meta: 0
        amount: 1
        enchantments:
          protection:
            level: 1
    amount: 1
    block: "42:0"
```

**Comment by JackMD** [comment]
I cannot reproduce this.
I used the following configuration:
```
  common:
    drops:
      - name: "G Sword"
        id: 276
        meta: 0
        amount: 1
        enchantments:
          protection:
            level: 3
          unbreaking:
            level: 5
    amount: 1
    block: "173:0"
```

**Comment by Haxley** [comment]
I figured it out, it depends on PiggyCustomEnchants for vanilla enchantments to work. If you don't have PiggyCustomEnchants installed, it will throw an error if you open a crate with an enchanted item.  

It wasn't throwing an error for me because I also had the Vanilla Enchantments plugin by TheAz928 installed to substitute other vanilla enchantments that aren't implemented in core PMMP. Once I removed the Vanilla Enchantments plugin, it started throwing the PiggyCustomEnchants error. 

Now that I have PiggyCustomEnchants installed, it's not throwing errors and is working great except my diamond sword enchanted with sharpness. Crate still just gives diamond sword with custom name, no enchantment, no error. 
```
  rare:
      - name: "§d§lEpsilon Sword"
        id: 276
        meta: 0
        amount: 1
        enchantments:
          sharpness:
            level: 1
    amount: 1
    block: "42:0"
```
